# -*- coding: utf-8 -*-
"""09040625096 - Revaldi Samudra Akbar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HnN3JBl9VgLZe8ghFcBn3P90Zwpdp8C

# Random Forest

## Impor Paket
"""

# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

"""## Memuat Data"""

import pandas as pd
bank_data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')

"""## Prapemrosesan Data untuk Random Forest Classifier"""

bank_data['Outcome'] = bank_data['Outcome'].map({0: 0, 1: 1})

"""## Membagi Data"""

# Split the data into features (X) and target (y)
X = bank_data.drop('Outcome', axis=1)
y = bank_data['Outcome']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

"""## Melakukan Fitting dan Evaluasi Model Random Forest"""

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

"""## Memvisualisasikan Hasil"""

# Export the first three decision trees from the forest

for i in range(3):
    tree = rf.estimators_[i]
    dot_data = export_graphviz(tree,
                               feature_names=X_train.columns,
                               filled=True,
                               max_depth=2,
                               impurity=False,
                               proportion=True)
    graph = graphviz.Source(dot_data)
    display(graph)

"""
## Tuning Hyperparameter"""

param_dist = {
    'n_estimators': randint(100, 500),
    'max_depth': randint(3, 15),
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5)
}

# Create a random forest classifier
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

# Use random search to find the best hyperparameters
rand_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=10,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    random_state=42
)  # <-- Pastikan tanda kurung tutup ini ada di sini!

# Create a variable for the best model
rand_search.fit(X_train, y_train)
best_rf = rand_search.best_estimator_

# Print the best hyperparameters
print('Best hyperparameters:', rand_search.best_params_)

"""## Metrik Evaluasi Random Forest Lainnya"""

# Generate predictions with the best model
y_pred = best_rf.predict(X_test)

# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred)

ConfusionMatrixDisplay(confusion_matrix=cm).plot();

y_pred = best_rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)